# Naive Bayes 실습

# 1. Gaussian Naive Bayes

- 데이터, 모듈 불러오기

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
import pandas as pd

In [3]:
iris = datasets.load_iris()
df_X=pd.DataFrame(iris.data)
df_Y=pd.DataFrame(iris.target)

In [4]:
df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [5]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

- 모델 피팅

In [6]:
gnb=GaussianNB()
fitted=gnb.fit(iris.data,iris.target)
y_pred=fitted.predict(iris.data)

In [7]:
fitted.predict_proba(iris.data)[[1,48,51,100]]

array([[  1.00000000e+000,   1.48206242e-017,   2.29743996e-025],
       [  1.00000000e+000,   2.70414239e-018,   2.86492790e-025],
       [  6.18854779e-101,   9.45169639e-001,   5.48303606e-002],
       [  4.13779546e-251,   6.35381030e-011,   1.00000000e+000]])

In [8]:
fitted.predict(iris.data)[[1,48,51,100]]

array([0, 0, 1, 2])

- Confusion matrix 구하기

In [9]:
from sklearn.metrics import confusion_matrix

In [10]:
confusion_matrix(iris.target,y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

- Prior 설정하기

In [11]:
gnb2=GaussianNB(priors=[1/100,1/100,98/100])
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]])

In [12]:
gnb2=GaussianNB(priors=[1/100,98/100,1/100])
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]])

# 2. Multinomial naive bayes

- 모듈 불러오기 및 데이터 생성

In [13]:
from sklearn.naive_bayes import MultinomialNB

In [14]:
import numpy as np

In [15]:
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [16]:
X

array([[4, 0, 4, 0, 3, 4, 1, 3, 3, 3, 0, 1, 2, 2, 0, 1, 4, 4, 0, 4, 3, 3,
        3, 4, 3, 0, 4, 2, 0, 2, 2, 3, 1, 4, 4, 0, 0, 0, 2, 4, 1, 1, 1, 1,
        0, 2, 3, 0, 2, 0, 0, 3, 2, 2, 1, 1, 0, 1, 0, 1, 3, 3, 2, 2, 3, 3,
        2, 4, 3, 4, 1, 3, 2, 1, 0, 1, 3, 4, 0, 2, 2, 4, 2, 1, 0, 3, 2, 0,
        2, 0, 3, 3, 1, 4, 1, 3, 3, 4, 2, 3],
       [2, 4, 2, 4, 4, 2, 0, 0, 1, 2, 1, 1, 1, 4, 0, 1, 4, 3, 1, 2, 1, 4,
        1, 2, 4, 2, 1, 2, 4, 3, 4, 4, 1, 4, 4, 0, 4, 2, 4, 0, 0, 0, 2, 4,
        0, 0, 1, 4, 3, 3, 4, 1, 1, 1, 2, 0, 4, 2, 0, 0, 2, 0, 2, 2, 1, 1,
        2, 0, 3, 2, 2, 0, 2, 4, 2, 1, 0, 2, 4, 4, 0, 0, 3, 3, 2, 0, 4, 2,
        3, 4, 2, 2, 4, 2, 4, 0, 2, 1, 4, 0],
       [2, 4, 4, 2, 0, 1, 3, 2, 0, 4, 3, 1, 1, 1, 4, 1, 1, 4, 2, 2, 4, 4,
        3, 4, 0, 2, 2, 2, 2, 4, 0, 3, 2, 3, 2, 0, 0, 2, 2, 0, 4, 1, 0, 4,
        1, 4, 0, 1, 2, 1, 4, 2, 3, 3, 0, 0, 0, 3, 1, 0, 4, 0, 2, 1, 4, 1,
        2, 3, 0, 2, 2, 3, 2, 3, 1, 1, 0, 1, 1, 3, 3, 4, 1, 0, 4, 3, 2, 0,
        1, 0, 1, 0, 1,

In [17]:
y

array([1, 2, 3, 4, 5, 6])

- Multinomial naive bayes 모델 생성

In [18]:
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
print(clf.predict(X[2:3]))

[3]


In [22]:
clf.predict_proba(X[2:3])

array([[  3.16232594e-28,   5.87205419e-35,   1.00000000e+00,
          1.57568740e-31,   6.46287158e-38,   2.97680104e-35]])

- prior 변경해보기

In [26]:
clf2 = MultinomialNB(class_prior=[0.1,0.5,0.1,0.1,0.1,0.1])
clf2.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=[0.1, 0.5, 0.1, 0.1, 0.1, 0.1],
       fit_prior=True)

In [27]:
clf2.predict_proba(X[2:3])

array([[  3.16232594e-28,   2.93602710e-34,   1.00000000e+00,
          1.57568740e-31,   6.46287158e-38,   2.97680104e-35]])